# Generated by Django 4.2.7 on 2023-11-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="dailystatus",
            field=models.CharField(
                default="", max_length=500, verbose_name="庫存資訊&調貨狀況"
            ),
        ),
    ]
