# Generated by Django 4.2.7 on 2023-11-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_goods_dailystatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyinout",
            name="countQuantity",
            field=models.FloatField(blank=True, null=True, verbose_name="盤點數量(件)"),
        ),
        migrations.AlterField(
            model_name="dailyinout",
            name="exportQuantity",
            field=models.FloatField(blank=True, null=True, verbose_name="出貨數量(件)"),
        ),
        migrations.AlterField(
            model_name="dailyinout",
            name="purchaseQuantity",
            field=models.FloatField(blank=True, null=True, verbose_name="進貨數量(件)"),
        ),
        migrations.AlterField(
            model_name="dailyinout",
            name="status",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="調貨狀況or進出貨資訊"
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="dailystatus",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                verbose_name="庫存資訊&調貨狀況",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="position2",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="儲位2"
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="position3",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="儲位3"
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="reason",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="未調貨原因"
            ),
        ),
    ]
