# Generated by Django 4.2.7 on 2023-11-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_dailyinout_goodsinout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyinout",
            name="countQuantity",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="盤點數量(件)"
            ),
        ),
        migrations.AlterField(
            model_name="dailyinout",
            name="exportQuantity",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="出貨數量(件)"
            ),
        ),
        migrations.AlterField(
            model_name="dailyinout",
            name="purchaseQuantity",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="進貨數量(件)"
            ),
        ),
    ]
