# Generated by Django 4.2.7 on 2023-11-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_dailyinout_countquantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goods",
            name="position",
        ),
    ]
